# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pascal Precht
tagline:          'Thoughts on Vim mastery and the future of the web'
description:      'Pascal Precht. Vimthusiast. Loves gifs. Runs <a href="http://thoughtram.io">thoughtram</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Pascal Precht'
  url:            https://twitter.com/PascalPrecht

github:
  repo:           https://github.com/PascalPrecht
