# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pascal Precht
tagline:          'Thoughts Vim mastery and the future of the web'
description:      'Pascal is a professional animated gif executer, Vimthusiast, in <span style="color: red;">&hearts;</span> with Web Components and teaches people technologies at <a href="http://twitter.com/thoughtram">@thoughtram</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Pascal Precht'
  url:            https://twitter.com/PascalPrecht

paginate:         5

github:
  repo:           https://github.com/PascalPrecht
