# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pascal Precht
tagline:          'Thoughts on pragmatic programming, Vim mastery and public speaking'
description:      'Pascal is a professional animated gif executer, sitting on a <a href="http://twitter.com/sofa_io">@sofa_io</a> at <a href="http://couchcommerce.com">@CouchCommerce</a>.'
description_2: 'Vimthusiast and also into high-fiving stewardesses.'
url:              http://lanyon.getpoole.com

author:
  name:           'Pascal Precht'
  url:            https://twitter.com/PascalPrecht

paginate:         5

github:
  repo:           https://github.com/PascalPrecht
