baseurl = "https://pascalprecht.github.io" # Hostname (and path) to the root.
title = "Pascal Precht" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-US" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsUseClasses=true
pygmentscodefences = false # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

googleAnalytics = 'UA-34513648-1'

[params] # theme parameters
    author = "Pascal Precht" # Author's name.
    info = "Super friendly Software Engineer" # Author's job title or info.
    description = "Pascal Precht's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "https://pbs.twimg.com/profile_images/993785060733194241/p3oAIMDP_400x400.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = ['/css/styles.css']

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Twitter"
    icon = "twitter"
    weight = 1
    url = "https://twitter.com/PascalPrecht/"
[[params.social]]
    name = "Github"
    icon = "github"
    weight = 2
    url = "https://github.com/PascalPrecht/"
[[params.social]]
    name = "StackOverflow"
    icon = "stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/1531806/pascal-precht?tab=profile"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

